### ISSUE TITLE
This theme also works on Linux

### ISSUE THREAD

**Issue by clsty** [yozhic/GoldenDict-Full-Dark-Theme#1]
Hi, thank you for sharing this theme, it looks really good.

I'm actually using it on Arch Linux and it works flawlessly, so it's actually not only on Windows.

**Comment by yozhic** [comment]
Thanks for your note! In theory this should work on any system, since it addresses Qt, not directly to the system. But once on macOS I had to change some rules because they didn't work the same way on Windows. So I decided to only announce a system that I could support if something happened.

But probably you're right, and I should add a note in the description about possible workability on other systems.
